# Generated by Django 5.1.5 on 2026-02-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class or emoji', max_length=40),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast Only'), ('half_board', 'Half Board (B+L or B+D)'), ('full_board', 'Full Board (B+L+D)'), ('all_inclusive', 'All Inclusive')], default='breakfast', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together={('property', 'meal_type')},
        ),
    ]
