# Generated by Django 5.1.5 on 2026-02-14 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list of amenities'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bed_type',
            field=models.CharField(choices=[('single', 'Single Bed'), ('double', 'Double Bed'), ('twin', 'Twin Beds'), ('queen', 'Queen Bed'), ('king', 'King Bed')], default='double', max_length=20),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_size_sqm',
            field=models.PositiveIntegerField(blank=True, help_text='Room size in square meters', null=True),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.URLField()),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
