# Generated by Django 5.1.5 on 2026-02-15 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomtype_amenities_roomtype_bed_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='amenities',
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
