# Generated by Django 5.1.5 on 2026-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.CharField(choices=[('hotel', 'Hotel'), ('bus', 'Bus'), ('cab', 'Cab'), ('package', 'Package')], max_length=20)),
                ('service_id', models.PositiveIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('demand_score', models.PositiveIntegerField(default=50)),
                ('occupancy_percent', models.PositiveIntegerField(default=50)),
                ('active_bookings', models.PositiveIntegerField(default=0)),
                ('available_inventory', models.PositiveIntegerField(default=0)),
                ('is_weekend', models.BooleanField(default=False)),
                ('season', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('peak', 'Peak')], default='normal', max_length=20)),
                ('competitor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('competitor_count', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['service_type', 'service_id', '-recorded_at'], name='pricing_pri_service_ef6297_idx'), models.Index(fields=['recorded_at'], name='pricing_pri_recorde_495aa9_idx'), models.Index(fields=['demand_score'], name='pricing_pri_demand__76375f_idx')],
            },
        ),
    ]
