# Generated by Django 5.1.5 on 2026-02-15 12:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebooking',
            name='end_date',
            field=models.DateField(validators=[core.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='start_date',
            field=models.DateField(validators=[core.validators.validate_future_date]),
        ),
    ]
