# Generated by Django 5.1.5 on 2026-02-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_packagebooking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebooking',
            name='public_booking_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
