"""Dashboard HTML generator"""

import json
import pathlib

def generate_dashboard():
    """Generate validator results dashboard"""
    
    results_path = pathlib.Path("results.json")
    if not results_path.exists():
        return
    
    with open(results_path) as f:
        data = json.load(f)
    
    # Calculate totals
    total_tests = len(data)
    total_failures = sum(len(v.get("errors", [])) for v in data.values())
    passed_tests = sum(1 for v in data.values() if not v.get("errors"))
    
    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Enterprise Validator Dashboard</title>
    <style>
        body {{ font-family: -apple-system,BlinkMacSystemFont,"Segoe UI","Roboto","Oxygen","Ubuntu","Cantarell","Fira Sans","Droid Sans","Helvetica Neue",sans-serif; margin: 20px; }}
        .summary {{ padding: 20px; border-radius: 8px; margin-bottom: 20px; }}
        .status {{ font-size: 24px; font-weight: bold; }}
        table {{ width: 100%; border-collapse: collapse; }}
        th, td {{ padding: 12px; text-align: left; }}
        .time {{ font-size: 12px; }}
        .error-list {{ padding: 10px; border-radius: 4px; margin-top: 10px; }}
        .error-item {{ margin: 5px 0; }}
    </style>
</head>
<body>
    <h1>⚙️ Enterprise Validator Dashboard</h1>
    
    <div class="summary">
        <div class="status">
            Status: <span class="{'pass' if total_failures == 0 else 'fail'}">
                {'✅ ALL SYSTEMS PASS' if total_failures == 0 else f'❌ {total_failures} FAILURES'}
            </span>
        </div>
        <p>Tests Passed: {passed_tests}/{total_tests}</p>
        <p>Total Failures: {total_failures}</p>
    </div>
    
    <table>
        <tr>
            <th>Test Module</th>
            <th>Status</th>
            <th>Time (ms)</th>
            <th>Details</th>
        </tr>
"""
    
    for test_name, test_data in sorted(data.items()):
        errors = test_data.get("errors", [])
        status = "✅ PASS" if not errors else "❌ FAIL"
        time_ms = test_data.get("time", 0)
        
        error_details = ""
        if errors:
            error_details = '<div class="error-list">'
            for err in errors:
                error_details += f'<div class="error-item">• {err}</div>'
            error_details += '</div>'
        
        html += f"""        <tr>
            <td><strong>{test_name}</strong></td>
            <td>{status}</td>
            <td class="time">{time_ms}</td>
            <td>{error_details}</td>
        </tr>
"""
    
    html += """    </table>
    
    <div style="margin-top: 30px; font-size: 12px;">
        <p>Generated by Enterprise Validator System | All validations run in real Chromium browser</p>
    </div>
</body>
</html>"""
    
    with open("dashboard.html", "w", encoding="utf-8") as f:
        f.write(html)

if __name__ == "__main__":
    generate_dashboard()